# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "Mediator"
description: > # this means to ignore newlines until "email:"
   A Jekyll theme - Medium inspired

email: proaben@hotmail.com
#blog logo
logo: "/assets/images/df_logo.jpg"
# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'Sherlock Tsai'
author: 'Sherlock Tsai'
#author_image: "/assets/images/author.jpg"
author_image: "https://farm8.staticflickr.com/7350/buddyicons/58674088@N00_r.jpg"
paginate:	5

url: "http://dearsherlock.github.io/" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
#  - icon:	twitter
#    url:	https://twitter.com/dirkfabisch
#    desc: Follow me on twitter
#    share_url: http://twitter.com/share
#    share_title: ?text=
#    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/dearsherlock
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
