# Site
name: "Coding Nightmare"
description: "Sherlock's Diary"
meta_description: "Sherlock's Diary"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
url:     'http://dearsherlock.github.com'
#baseurl: /mediumish-theme-jekyll
google_analytics: 'UA-63838656-1'
#disqus: 'demowebsite'
mailchimp-list: 'https://cht.us19.list-manage.com/subscribe?u=8a08b1f2d7d9ea67880a0ee38&id=cb9be09bf6'
# Authors
authors:
  sherlock:
    name: Sherlock
    display_name: Sherlock
    gravatar: 70ba0df8e3d086bd4ef10e6c331a1f5f
    email: tw.sherlock@gmail.com
    web: http://dearsherlock.github.io/
    twitter: https://medium.com/@proaben
    description: "宅爸"
  john:
    name: John
    display_name: John
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: wowthemesnet@gmail.com
    web: https://www.wowthemes.net
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
highlighter: rouge