# Site settings
title: Coding Nightmare
email: proaben@hotmail.com
description: "Test" 
baseurl: "" 
url: "dearsherlock.github.com" # the base hostname & protocol for your site
github_username:  dearsherlock

# Build settings
markdown: kramdown
